dist: trusty

sudo: required

language: generic

env:
  global:
    - TIMEOUT=30

cache:
  - apt

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release CATKIN_CONFIG_OPTIONS="-DCMAKE_BUILD_TYPE=Release"

# Install test fixture dependencies.
before_install:
  - mkdir -p "${HOME}/workspace/src"
  - cd "${HOME}/workspace"
  - git clone https://github.com/personalrobotics/pr-cleanroom.git scripts
  - curl -sS "${DISTRIBUTION}" > distribution.yml
  - ./scripts/internal-setup.sh
  - export PACKAGE_NAMES="$(./scripts/internal-get-packages.py distribution.yml ${REPOSITORY})"

install:
  - mv "${TRAVIS_BUILD_DIR}" src
  - ./scripts/internal-distro.py --workspace=src distribution.yml --repository "${REPOSITORY}"

script:
  - ./scripts/internal-build.sh ${PACKAGE_NAMES}

after_failure:
  - cat ./build/ada_description/Testing/Temporary/LastTest.log
  - cat ./build/ada_description/Testing/Temporary/LastTestsFailed.log
